allowBuilds:
  '@parcel/watcher': false
  esbuild: false
  unrs-resolver: false
  vue-demi: false
  '@tailwindcss/oxide': true
  better-sqlite3: true
  canvas: true
  sharp: true

patchedDependencies:
  fabric: patches/fabric.patch

shamefullyHoist: true
