onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - canvas
  - esbuild
  - sharp
  - unrs-resolver
  - vue-demi

patchedDependencies:
  fabric: patches/fabric.patch

shamefullyHoist: true
